name: Test Eval Scripts
on:
  push:
    branches: ["master"]
  
permissions:
  id-token: write
  contents: read

jobs:
  download-from-s3: # do for tabular first
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.9'
      - name: Setup npm
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::369469875935:role/AutoGluonCIBenchmark
          role-duration-seconds: 14400
          aws-region: us-east-1
      - name: Install AG Bench Using PyPi + Evaluate (change to source later)
        shell: bash -l {0}
        run: |
          nvm install 20
          npm install -g aws-cdk
          /bin/bash ./.github/workflow_scripts/test_evaluate.sh tabular 1h
