name: Test Eval Scripts
on:
  push:
    branches: ["timeseries_bench"]
  
permissions:
  id-token: write
  contents: read

jobs:
  download-from-s3: # do for tabular first
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Env Vars
        uses: ./.github/actions/setup-env-vars
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::369469875935:role/AutoGluonCIBenchmarkConfig
          role-duration-seconds: 3600
          aws-region: us-east-1
      - name: Install AG Bench Using PyPi + Evaluate (change to source later)
        run: |
          /bin/bash ./.github/workflow_scripts/test_evaluate.sh tabular 1h
